services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/app:/usr/src/app/data
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./volumes/nginx:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  db:
