### Login
POST http://localhost/api/login
accept: application/json
content-type: application/json
accept: */*
accept-encoding: gzip, deflate, br

{
    "username": "User1",
    "password": "dsfsdfsdfsdfsf"
}
