### GET request to example server
POST http://localhost:3000/api/register
accept: application/json
content-type: application/json
accept: */*
accept-encoding: gzip, deflate, br

{
  "username": "User1",
  "password": "dsfsdfsdfsdfsf"
}
